from pyfiglet import Figlet
from faker import Faker
c_text = Figlet(font="slant")
print(c_text.renderText("MADE BY"))
print(c_text.renderText("OMERTA"))
#FAKER-SCRIPT
fake = Faker()
print("Choose One Of This: [All]  [Person] ")
print("If You Choose [All] You Will Get All Fake Informations")
print("And If You Choose [Person] You Will Get Many Fake Gen Informations")
choose = input("Choose What Do You Want: ")
if choose == "All":
    print("‐-----------------------------------------------")
    print("Full Name:")
    print(fake.name())
    print("‐-----------------------------------------------")
    print("Country:")
    print(fake.country())
    print("‐-----------------------------------------------")
    print("City:")
    print(fake.city())
    print("‐-----------------------------------------------")
    print("Address:")
    print(fake.address())
    print("‐-----------------------------------------------")
    print("Phone Number:")
    print(fake.phone_number())
    print("‐-----------------------------------------------")
    print("Email:")
    print(fake.email())
    print("‐-----------------------------------------------")
    print("Website:")
    print(fake.url())
    print("‐-----------------------------------------------")
    print("Latitude:")
    print(fake.latitude())
    print("‐-----------------------------------------------")
    print("Longitude:")
    print(fake.longitude())
    print("‐-----------------------------------------------")
elif choose == "Person":
    print("Person Info")
    print(fake.simple_profile(sex=None))
else:
    print("‐-----------------------------------------------")
    print("PLEASE TRY AGAIN")
